# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5c4c7ddfaddf3322cef406b333dfcd3"
name = "GD: Wholesale Pro"
application_url = "https://gd-wholesale-pro.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products, read_discounts, write_discounts, read_customers, write_customers"

[auth]
redirect_urls = [
    "https://gd-wholesale-pro.onrender.com/auth/callback",
    "https://gd-wholesale-pro.onrender.com/auth/shopify/callback",
    "https://gd-wholesale-pro.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://gd-wholesale-pro.onrender.com/api"
subpath = "proxy"
prefix = "apps"

[variant.metafields.app.gd_b2b_price]
type = "number_decimal"
name = "GD B2B Price"
access.admin = "merchant_read"